### ISSUE TITLE
Upload the installer package as a Release on GitHub

### ISSUE THREAD

**Issue by roryokane** [aparks517/convert-websters#6]
[In the README](https://github.com/aparks517/convert-websters#if-you-just-want-the-results), there is an “installer package” link that links to a third-party site, http://parksdigital.com/Webster%27s%20Unabridged%20Dictionary.pkg.

I didn’t feel safe running that installer straight away, because linking to a third-party site is unusual in GitHub READMEs. I reasoned that domains can be stolen, so I should check out the site first. Thankfully, http://parksdigital.com/ does appear to be affiliated with your user @aparks517.

The link would feel more trustworthy if it pointed to a [Release in this GitHub repository](https://github.com/aparks517/convert-websters/releases). Hosting the file on GitHub would save you bandwidth too.

**Comment by aparks517** [comment]
If you're concerned about the provenance (as is reasonable), I would recommend examining the source and making your own build. The Internet's a wild place!
